def_regex = "(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+) - - \\[(?P<datetime>[^\\]]+)\\] \"(?P<method>\\w+) (?P<uri>[^ ]+) (?P<protocol>[^\"]+)\" (?P<status>\\d+) (?P<size>\\d+) \"(?P<referrer>[^\"]*)\" \"(?P<user_agent>[^\"]*)\""

# log files
[log.laegis]
path = "/tmp/access.log"
regex = "(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+) - - \\[(?P<datetime>[^\\]]+)\\] \"(?P<method>\\w+) (?P<uri>[^ ]+) (?P<protocol>[^\"]+)\" (?P<status>\\d+) (?P<size>\\d+) \"(?P<referrer>[^\"]*)\" \"(?P<user_agent>[^\"]*)\""



#
# Stages: onload, tagging, rate, session, out
#
[query.logintag]
# successful login
query="uri=='/client/dashboard' and method=='GET' and status==200"
stage="tagging"
tag="LOGIN"

[query.login]
# any login attempt
query="uri=='/login' and method=='POST'"
stage="out"

[query.post]
query="method=='POST'"
stage="rate"
counter="postrate"

[query.short]
query="duration_sec < 600"
stage="session"

[query.realuser]
query="'LOGIN' in tags"
stage="session"


